name: CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Installation
      run: npm install
    - name: Testing
      run: npm test -- --coverage
    - name: Codecov
      uses: codecov/codecov-action@v1.0.13
    - name: Build
      run: CI=false npm run build
    - name: Deploy to firebase
      uses: w9jds/firebase-action@master
      with:
       args: deploy --only hosting
    env:
     FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
