name: CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Installation
      run: npm install
    - name: Testing
      run: npm test
    - name: Test & publish code coverage
      uses: paambaati/codeclimate-action@v2.6.0
      env:
        CC_TEST_REPORTER_ID: caf391a8e84d285ef0cd83011a2ff82a6c67e08dd015a7dac360ba2e7d30e57c
      with:
        coverageCommand: npm test -- --coverage --watchAll=false
    - name: Build
      run: CI=false npm run build
    - name: Deploy to firebase
      uses: w9jds/firebase-action@master
      with:
       args: deploy --only hosting
    env:
     FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
